// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgowey2GkcF9WBveEsTjqQz7q3CFnPrzE',
    appId: '1:610332152435:web:7f4eb647597f90b30ad006',
    messagingSenderId: '610332152435',
    projectId: 'cgpa-calculator-eecb4',
    authDomain: 'cgpa-calculator-eecb4.firebaseapp.com',
    storageBucket: 'cgpa-calculator-eecb4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCU3ezubS8h3J2Pl8dmPJsoz0ydN3DH68',
    appId: '1:610332152435:android:05c1abbbe98835910ad006',
    messagingSenderId: '610332152435',
    projectId: 'cgpa-calculator-eecb4',
    storageBucket: 'cgpa-calculator-eecb4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALO8fhGBNVBkHukqWvkqwdBVuhwAaelQQ',
    appId: '1:610332152435:ios:5dd399969ffa3cf80ad006',
    messagingSenderId: '610332152435',
    projectId: 'cgpa-calculator-eecb4',
    storageBucket: 'cgpa-calculator-eecb4.appspot.com',
    iosBundleId: 'com.example.yctCgpaCalculator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALO8fhGBNVBkHukqWvkqwdBVuhwAaelQQ',
    appId: '1:610332152435:ios:5dd399969ffa3cf80ad006',
    messagingSenderId: '610332152435',
    projectId: 'cgpa-calculator-eecb4',
    storageBucket: 'cgpa-calculator-eecb4.appspot.com',
    iosBundleId: 'com.example.yctCgpaCalculator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcoGztBd-FHG0EmyIGKftwAD8PUxMajgE',
    appId: '1:610332152435:web:82dd42566a435dfb0ad006',
    messagingSenderId: '610332152435',
    projectId: 'cgpa-calculator-eecb4',
    authDomain: 'cgpa-calculator-eecb4.firebaseapp.com',
    storageBucket: 'cgpa-calculator-eecb4.appspot.com',
  );
}
